# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=mos-machine-ssa -verify-machineinstrs -o - %s | FileCheck %s
---
name: phi
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LDImm:%[0-9]+]]:gpr = LDImm 0
  ; CHECK-NEXT:   BR %bb.2, $c, 1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LDImm1:%[0-9]+]]:gpr = LDImm 1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[LDImm]], %bb.0, [[LDImm1]], %bb.1
  ; CHECK-NEXT:   RTS implicit [[PHI]]
  bb.0:
    liveins: $c
    %0:gpr = LDImm 0
    BR %bb.2, $c, 1
  bb.1:
    %0:gpr = LDImm 1
  bb.2:
    RTS implicit %0
...
---
name: dead_phi
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: dead_phi
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BR %bb.2, $c, 1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[LDImm:%[0-9]+]]:gpr = LDImm 1
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY [[LDImm]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RTS
  bb.0:
    liveins: $c
    BR %bb.2, $c, 1
  bb.1:
    %0:gpr = LDImm 1
    %1:gpr = COPY %0
  bb.2:
    RTS
...
---
name: subreg
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $a
    ; CHECK-LABEL: name: subreg
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:imag16 = IMPLICIT_DEF
    ; CHECK-NEXT: [[INSERT_SUBREG:%[0-9]+]]:imag16 = INSERT_SUBREG [[DEF]], [[COPY]], %subreg.sublo
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: [[INSERT_SUBREG1:%[0-9]+]]:imag16 = INSERT_SUBREG [[INSERT_SUBREG]], [[COPY1]], %subreg.subhi
    undef %0.sublo:imag16 = COPY $a
    %0.subhi:imag16 = COPY $a
...
