# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=mos-reg-alloc -verify-machineinstrs -o - %s | FileCheck %s
---
name: rts
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $a, $x
    ; CHECK-LABEL: name: rts
    ; CHECK: liveins: $a, $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RTS implicit $a, implicit $x
    RTS implicit $a, implicit $x
...
---
name: phys-reg-copy
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $a
    ; CHECK-LABEL: name: phys-reg-copy
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: RTS implicit $a
    %0:anyi8 = COPY $a
    $a = COPY %0
    RTS implicit $a
...
---
name: across-mbb
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: across-mbb
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $a
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $a
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RTS implicit $a
  bb.0:
    liveins: $a
    %0:anyi8 = COPY $a
    JMP %bb.1

  bb.1:
    $a = COPY %0
    RTS implicit $a
...
---
name: untracked-phys-reg
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $rc1
    ; CHECK-LABEL: name: untracked-phys-reg
    ; CHECK: $rc2 = COPY $rc1
    ; CHECK-NEXT: RTS
    $rc2 = COPY $rc1
    RTS
...
---
name: simple-vreg
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: simple-vreg
    ; CHECK: $x = LDAbs 1234
    ; CHECK-NEXT: STAbs $x, 1234
    ; CHECK-NEXT: RTS
    %0:gpr = LDAbs 1234
    STAbs %0, 1234
    RTS
...
---
name: unused-physreg-def
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: unused-physreg-def
    ; CHECK: $x = LDAbs 1234
    ; CHECK-NEXT: STAbs $x, 1234, implicit-def $c
    ; CHECK-NEXT: RTS
    %0:gpr = LDAbs 1234
    STAbs %0, 1234, implicit-def $c
    RTS
...
---
name: conflicting-defs
## %0 would tend towards the $x register, but the implicit def prevents this.
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: conflicting-defs
    ; CHECK: $y = LDAbs 1234, implicit-def $x
    ; CHECK-NEXT: STAbs $y, 1234
    ; CHECK-NEXT: RTS
    %0:gpr = LDAbs 1234, implicit-def $x
    STAbs %0, 1234
    RTS
...
---
name: reg-copy
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: reg-copy
    ; CHECK: $x = LDAbs 1234
    ; CHECK-NEXT: $a = COPY $x
    ; CHECK-NEXT: RTS implicit $a, implicit $x
    %0:gpr = LDAbs 1234
    $a = COPY %0
    $x = COPY %0
    RTS implicit $a, implicit $x
...
---
name: spill-reload-to-imag
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: spill-reload-to-imag
    ; CHECK: $a = LDAbs 1234
    ; CHECK-NEXT: $y = LDAbs 1235
    ; CHECK-NEXT: $x = LDAbs 1236
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:imag8(s8) = COPY $y
    ; CHECK-NEXT: $y = LDAbs 1237
    ; CHECK-NEXT: STAbs $a, 1234
    ; CHECK-NEXT: $a = COPY [[COPY]](s8)
    ; CHECK-NEXT: STAbs $a, 1234
    ; CHECK-NEXT: STAbs $x, 1234
    ; CHECK-NEXT: STAbs $y, 1234
    ; CHECK-NEXT: RTS
    %0:gpr = LDAbs 1234
    %1:gpr = LDAbs 1235
    %2:gpr = LDAbs 1236
    %3:gpr = LDAbs 1237
    STAbs %0, 1234
    STAbs %1, 1234
    STAbs %2, 1234
    STAbs %3, 1234
    RTS
...
