# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=mos -run-pass=mos-regalloc -o - %s | FileCheck %s
---
name: simple_load_store
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: simple_load_store
    ; CHECK: $a = LDAbs 1234
    ; CHECK-NEXT: STAbs killed $a, 4567
    %0:gpr = LDAbs 1234
    STAbs killed %0, 4567
...

# Narrowing: COPY %0 defines %1:Ac while %0:GPR is still live (non-kill use).
# GPR overlaps Ac (both contain A), so %0's effective class is narrowed
# from {A,X,Y} to {X,Y} to prove colorability.
---
name: narrowing
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: ac }
body: |
  bb.0:
    ; CHECK-LABEL: name: narrowing
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: STAbs $a, 3000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: STAbs killed $a, 2000
    %0:gpr = LDAbs 1000
    %1:ac = COPY %0
    STAbs %1, 2000
    STAbs %0, 3000
...

# Multi-round narrowing: when %2:Ac is defined, both %0:GPR and %1:GPR are
# still live. Each contributes 1 to %2's interference (Σ=2, |Ac.Eff|=1, slack
# = -1). Narrowing one GPR off A is not enough — slack rises to 0; a second
# GPR must be narrowed for slack to reach 1.
---
name: chained_narrowing
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
  - { id: 2, class: ac }
body: |
  bb.0:
    ; CHECK-LABEL: name: chained_narrowing
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: STAbs $a, 4000
    ; CHECK-NEXT: $x = COPY $a
    ; CHECK-NEXT: STAbs killed $x, 5000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: STAbs killed $a, 3000
    %0:gpr = LDAbs 1000
    %1:gpr = COPY %0
    %2:ac  = COPY %0
    STAbs killed %2, 3000
    STAbs killed %0, 4000
    STAbs killed %1, 5000
...

# Livein: $a is live at MBB entry, COPY'd into %0:Ac. The livein cluster
# publishes $a; linearizeClusters folds the COPY's cluster into it, so the
# COPY is allocated with $a live and reuses it.
---
name: livein
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $a
    ; CHECK-LABEL: name: livein
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: STAbs killed $a, 1000
    %0:ac = COPY $a
    STAbs killed %0, 1000
...

# Livein consumer that is not the first instruction, alongside an independent
# load/store chain. linearizeClusters folds both chains into the livein
# cluster. Because the independent %0 is colored while the livein $a is still
# live — its consumer, the COPY, is folded later — %0 must avoid $a: it gets
# $x, not $a, so the livein survives to its use. This is the livein interference
# being honored at fold time (the COPY chain need not be forced first).
---
name: livein_non_first
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: ac }
body: |
  bb.0:
    liveins: $a
    ; CHECK-LABEL: name: livein_non_first
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDAbs 1000
    ; CHECK-NEXT: STAbs killed $x, 2000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: STAbs killed $a, 3000
    %0:gpr = LDAbs 1000
    %1:ac = COPY $a
    STAbs killed %0, 2000
    STAbs killed %1, 3000
...

# Linearization: two independent load-store pairs share no def-use, so the
# greedy mergeClusters pass leaves them as separate clusters. linearizeClusters
# then folds both into the livein cluster.
---
name: linearize_disconnected
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: linearize_disconnected
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: STAbs killed $a, 2000
    ; CHECK-NEXT: $a = LDAbs 3000
    ; CHECK-NEXT: STAbs killed $a, 4000
    %0:gpr = LDAbs 1000
    STAbs killed %0, 2000
    %1:gpr = LDAbs 3000
    STAbs killed %1, 4000
...

# Tied def: %0 is single-use; the tied def %1 inherits %0's physreg via
# look-through. normalizeTiedRegs leaves the tie untouched (matching
# classes, single use).
---
name: tied_def
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: tied_def
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: $a = INC killed $a
    ; CHECK-NEXT: STAbs killed $a, 2000
    %0:gpr = LDAbs 1000
    %1:gpr = INC killed %0
    STAbs killed %1, 2000
...

# Tied chain: %0 → %1 → %2 share one slot via two chained ties. Verifies
# that tiedRoot resolves transitively (the second INC's tied use is %1, a
# tied def whose root is %0).
---
name: tied_chain
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
  - { id: 2, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: tied_chain
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: $a = INC killed $a
    ; CHECK-NEXT: $a = INC killed $a
    ; CHECK-NEXT: STAbs killed $a, 2000
    %0:gpr = LDAbs 1000
    %1:gpr = INC killed %0
    %2:gpr = INC killed %1
    STAbs killed %2, 2000
...

# Tied multi-use: %0 has two uses, so normalizeTiedRegs inserts a save
# COPY before the INC. The COPY's def %3 owns the tied slot; %0 stays
# live for the unrelated store.
---
name: tied_multi_use
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: tied_multi_use
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: STAbs $a, 2000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: $a = INC killed $a
    ; CHECK-NEXT: STAbs killed $a, 3000
    %0:gpr = LDAbs 1000
    %1:gpr = INC %0
    STAbs killed %0, 2000
    STAbs killed %1, 3000
...

# Dead solitary def: a whole instruction's only def is dead. The vreg's
# slot doesn't extend past MI, so the following load reuses $a.
---
name: dead_def_solitary
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: dead_def_solitary
    ; CHECK: dead $a = LDAbs 1000
    ; CHECK-NEXT: $a = LDAbs 2000
    ; CHECK-NEXT: STAbs killed $a, 3000
    dead %0:gpr = LDAbs 1000
    %1:gpr = LDAbs 2000
    STAbs killed %1, 3000
...

# Dead vreg def alongside a live def: ASL produces a live shifted value
# (tied to its input) and a carry output we don't care about. The dead
# carry vreg gets $c, but $c is freed after MI.
---
name: dead_def_with_live
tracksRegLiveness: true
registers:
  - { id: 0, class: ac }
  - { id: 1, class: ac }
  - { id: 2, class: cc }
body: |
  bb.0:
    ; CHECK-LABEL: name: dead_def_with_live
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: $a, dead $c = ASL killed $a
    ; CHECK-NEXT: STAbs killed $a, 2000
    %0:ac = LDAbs 1000
    %1:ac, dead %2:cc = ASL killed %0
    STAbs killed %1, 2000
...

# Tied dead def: RORAbs writes memory with a rotate; its carryout is
# tied to carryin. Marking the carryout dead exercises the tiedRoot
# redirect in the dead-erase pass — the slot's root is the carryin
# vreg, not the dead def itself.
---
name: dead_def_tied
tracksRegLiveness: true
registers:
  - { id: 0, class: cc }
  - { id: 1, class: cc }
body: |
  bb.0:
    ; CHECK-LABEL: name: dead_def_tied
    ; CHECK: $c = LSRAbs 1000 :: (load (s8) from `ptr null`), (store (s8) into `ptr null`)
    ; CHECK-NEXT: dead $c = RORAbs 2000, killed $c :: (load (s8) from `ptr null`), (store (s8) into `ptr null`)
    %0:cc = LSRAbs 1000 :: (load (s8) from `ptr null`), (store (s8) into `ptr null`)
    dead %1:cc = RORAbs 2000, killed %0 :: (load (s8) from `ptr null`), (store (s8) into `ptr null`)
...

# Bare terminator: RTS with no operands. Verifies the basic terminator-
# cluster path — the trailing RTS is its own atomic cluster, folded in
# last by linearizeClusters.
---
name: terminator_bare
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: terminator_bare
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: STAbs killed $a, 2000
    ; CHECK-NEXT: RTS
    %0:gpr = LDAbs 1000
    STAbs killed %0, 2000
    RTS
...

# Terminator with implicit physreg use: RTS reads $a (return value).
# The COPY into $a must precede RTS.
---
name: terminator_return_value
tracksRegLiveness: true
registers:
  - { id: 0, class: ac }
body: |
  bb.0:
    ; CHECK-LABEL: name: terminator_return_value
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: RTS implicit killed $a
    %0:ac = LDAbs 1000
    $a = COPY killed %0
    RTS implicit killed $a
...

# Interleaved: a non-$a-related cluster sits in MBB order between the
# $a-producing COPY and the RTS. Verifies that the greedy merge pass did
# NOT splice RTS up after the COPY — RTS must stay last.
---
name: terminator_interleaved
tracksRegLiveness: true
registers:
  - { id: 0, class: ac }
  - { id: 1, class: gpr }
body: |
  bb.0:
    ; CHECK-LABEL: name: terminator_interleaved
    ; CHECK: $a = LDAbs 2000
    ; CHECK-NEXT: STAbs killed $a, 3000
    ; CHECK-NEXT: $a = LDAbs 1000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: RTS implicit killed $a
    %0:ac = LDAbs 1000
    $a = COPY killed %0
    %1:gpr = LDAbs 2000
    STAbs killed %1, 3000
    RTS implicit killed $a
...

# Compare-and-branch with a vreg use: CmpBrImm uses %0:gpr, carries an
# undef $n flag-tag and implicit-def $c. Targets %bb.0 to keep single-
# BB form; followed by RTS to provide a fallthrough exit (so the bb is
# both predecessor and successor of itself, and exits via RTS). The
# CmpBrImm + RTS span is one atomic terminator cluster.
---
name: terminator_cmpbr_vreg
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
body: |
  bb.0:
    successors: %bb.0
    ; CHECK-LABEL: name: terminator_cmpbr_vreg
    ; CHECK: successors: %bb.0(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = LDAbs 1000
    ; CHECK-NEXT: CmpBrImm %bb.0, killed undef $n, 1, killed $a, 5, implicit-def dead $c
    ; CHECK-NEXT: RTS
    %0:gpr = LDAbs 1000
    CmpBrImm %bb.0, undef $n, 1, killed %0, 5, implicit-def $c
    RTS
...

# Cost-aware deferral + re-cost between commits. %0:Ac is COPY'd to the gpr
# connector %1 (so %1's def cluster keeps %0 live), then %0 dies, then %2:Ac
# is derived from %1 after %0 is dead. Input order is colorable: %0 and %2
# never overlap, so both can take $a. But the %1 edge offers a merge that
# would splice %2's $a def up next to %1's def while %0 (also $a, and Ac is
# not narrowable) is still live — an uncolorable $a/$a overlap. The scheduler
# costs that merge at 1 and instead commits the cost-0 merge that kills %0;
# once %0 is dead the same %1-edge merge re-costs to 0 and commits cleanly.
# A scheduler that committed merges greedily by edge order would take the
# cost-1 merge and trip commitMerge's colorability check.
---
name: cost_aware_deferral
tracksRegLiveness: true
registers:
  - { id: 0, class: ac }
  - { id: 1, class: gpr }
  - { id: 2, class: ac }
body: |
  bb.0:
    ; CHECK-LABEL: name: cost_aware_deferral
    ; CHECK: $a = LDAbs 1000
    ; CHECK-NEXT: STAbs $a, 2000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: STAbs killed $a, 3000
    %0:ac = LDAbs 1000
    %1:gpr = COPY %0
    STAbs killed %0, 2000
    %2:ac = COPY killed %1
    STAbs killed %2, 3000
...

# Ordering barrier: the dependence-graph triangle %0's def -> COPY -> store,
# with the store also using %0 directly. Merging the store's cluster straight
# into %0's def cluster would trap the COPY between the two halves of an
# atomic cluster (it must read %0 after its def and produce %1 before the
# store), so canMerge rejects that direction until the COPY's cluster has
# merged in. A cost-only scheduler without the legality gate could commit the
# store-into-def merge first (it is also cost 0), splicing the store's use of
# %1 ahead of %1's def.
---
name: vreg_data_triangle
tracksRegLiveness: true
registers:
  - { id: 0, class: ac }
  - { id: 1, class: xc }
body: |
  bb.0:
    ; CHECK-LABEL: name: vreg_data_triangle
    ; CHECK: $a = LDImm 1
    ; CHECK-NEXT: $x = COPY $a
    ; CHECK-NEXT: STAbsIdx killed $a, 200, killed $x
    %0:ac = LDImm 1
    %1:xc = COPY %0
    STAbsIdx killed %0, 200, killed %1
...

# The livein-consumer cluster (cluster 0) ends up merged INTO the LDImm's
# cluster as the use side: the store needs both the livein-derived %0 and the
# later-defined %1, so cluster 0's instructions are spliced from the front of
# the block to follow the LDImm. Exercises commitMerge's splice when the use
# cluster starts at MBB.begin() (no predecessor cluster to fix up).
---
name: livein_cluster_spliced
tracksRegLiveness: true
registers:
  - { id: 0, class: ac }
  - { id: 1, class: xc }
liveins:
  - { reg: '$a' }
body: |
  bb.0:
    liveins: $a
    ; CHECK-LABEL: name: livein_cluster_spliced
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImm 3
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: STAbsIdx killed $a, 100, killed $x
    %0:ac = COPY $a
    %1:xc = LDImm 3
    STAbsIdx killed %0, 100, killed %1
...

# Cost-aware linearization: two independent clusters become ready at the same
# time — %0:ac's load/store and a store of the livein $a. %0 needs $a (its only
# register), but $a is still live, so folding %0's cluster first is uncolorable
# (costs a copy). The store kills $a; folding it first frees $a, after which %0
# colors to it. So linearizeClusters must pick by cost, not layout/id order:
# the cheaper fold (the store) has to go first. A cost-blind linearize folds %0
# first and dies with "merge requires a copy" — this test guards against that.
---
name: cost_aware_linearize
tracksRegLiveness: true
registers:
  - { id: 0, class: ac }
body: |
  bb.0:
    liveins: $a
    ; CHECK-LABEL: name: cost_aware_linearize
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: STAbs killed $a, 1000
    ; CHECK-NEXT: $a = LDImm 5
    ; CHECK-NEXT: STAbs killed $a, 2000
    %0:ac = LDImm 5
    STAbs killed %0, 2000
    STAbs killed $a, 1000
...

# Boundary livein run of length >= 2: the two contiguous livein-reader COPYs
# fuse into one PCOPY, which persists into the output for ExpandPostRAPseudos.
# Assignment bias gives each vreg its paired livein register, so the parallel
# copy is all identities.
---
name: pcopy_livein_block
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $a, $x
    ; CHECK-LABEL: name: pcopy_livein_block
    ; CHECK: liveins: $a, $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a, $x = PCOPY killed $a, killed $x
    ; CHECK-NEXT: STAbs killed $a, 1000
    ; CHECK-NEXT: STAbs killed $x, 2000
    %0:gpr = COPY $a
    %1:gpr = COPY $x
    STAbs killed %0, 1000
    STAbs killed %1, 2000
...

# Boundary return run of length >= 2: the two contiguous return-writer COPYs
# (read by RTS) fuse into one PCOPY. The naive first-free assignment would cross
# the values (%0 produced first -> $a, but returned in $x), making the parallel
# copy a register swap. Assignment bias instead produces each value directly in
# its return register, so the PCOPY is all identities and no temporary is needed.
---
name: pcopy_return_block
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: pcopy_return_block
    ; CHECK: $a = LDAbs 2000
    ; CHECK-NEXT: $x = LDAbs 1000
    ; CHECK-NEXT: $x, $a = PCOPY killed $x, killed $a
    ; CHECK-NEXT: RTS implicit killed $a, implicit killed $x
    %0:gpr = LDAbs 1000
    %1:gpr = LDAbs 2000
    $x = COPY %0
    $a = COPY %1
    RTS implicit $a, implicit $x
...

# Pressure-aware merge tie-break. %0 (gpr, any GPR) is copied into %1 (ac, A-only)
# and both are stored. Cost alone cannot tell "keep %0 in $x and %1 in $a" (two
# registers held at once) apart from "route everything through $a" — both are
# copy-free, cost 0. The slack-aware secondary merge key prefers the lower-
# pressure schedule: %0 lands in $a and its store is hoisted to free the register
# before %1 is materialized (the residual $a = COPY $a identity is cleaned up
# downstream). Without the secondary key the greedy keeps %0 in $x, so these
# checks fail without it.
---
name: pressure_aware_tiebreak
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: ac }
body: |
  bb.0:
    ; CHECK-LABEL: name: pressure_aware_tiebreak
    ; CHECK: $a = LDAbs 1234
    ; CHECK-NEXT: STAbs $a, 5000
    ; CHECK-NEXT: $a = COPY killed $a
    ; CHECK-NEXT: STAbs killed $a, 6000
    %0:gpr = LDAbs 1234
    %1:ac = COPY %0
    STAbs %0, 5000
    STAbs %1, 6000
...
